int a = 3;
int b = 6;
int c = 9;
int d = 2;
int e = 1;
int max = a;
if (b > max) max = b;
if (c > max) max = c;
if (d > max) max = d;
if (e > max) max = e;
Console.Write("max= ");
Console.WriteLine(max);
